### PR TITLE
Support Ruby 2.2 & sync upstream with Shopify fork

### LINKED ISSUE #9: syck seems to not work on ruby 2.2.0p0 (2014-12-25 revision 49005) [i686-linux]
Hello,

This is an error possibly on ruby 2.2.0p0.
syck works perfectly fine on ruby 2.1.5 for me.

The error I get is when I try to do this here:

    YAML::ENGINE.yamler

I used this before to set syck.

When I do this, though, I immediately get this error:

    NameError: uninitialized constant Psych::Syck::ENGINE

Both psych and syck were required before I tried the above.

I assume something has changed in between these two ruby
versions but I am not quite sure how to trace back this error.

Thanks.

### PR DESCRIPTION
**Pull request by kirs**
fix #9
/cc @hsbt

### CODE REVIEW

**Comment by hsbt** [comment]
Thank you. I'm going to prepare to release syck 1.1.0

**Comment by kirs** [comment]
Awesome!

**Comment by kirs** [comment]
@hsbt any estimates when 1.1.0 would be available?

**Comment by hsbt** [comment]
Work in progress. I'm not full-time open source programmer.

**Comment by hsbt** [comment]
done https://rubygems.org/gems/syck/versions/1.1.0

**Pull request merged**
